[package]
name = "rust-roguelike2"
version = "0.1.0"
authors = ["awski <adam.wolanski@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.15.0"
rand = "0.8.0"